# Generated by Django 5.1.6 on 2025-04-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.articles', verbose_name='Новость'),
            preserve_default=False,
        ),
    ]
